---
title: "Data Manipulation"
author: "Xun Wang"
date: "9/19/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Import datasets

```{r}
litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

## Selecting!!!

```{r}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight)

select(litters_data, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

select(litters_data, litter_number, group, everything()) #reorganizing columns

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)

litters_selected = select(litters_data, group, litter_number, gd0_weight, pups_born_alive) # a new data frame is created

select(litters_data, GROUP = group, litter_number) #rename varibles while selecting

rename(litters_data, GROUP = group) #rename varibles without selecting
```

## Filtering !!!!!!

```{r}
filter(litters_data, group == "Mod8")

filter(litters_data, gd_of_birth == 20)

filter(litters_data, gd_of_birth < 20)

filter(litters_data, gd_of_birth >= 20)

filter(litters_data, pups_born_alive < 6)

filter(litters_data, pups_born_alive < 6, group == "Con7")

# to do "or" like filter(litters_data, group == "Con7" | group == "Con8")
# we'd better use the one below:
filter(litters_data, group %in% c("Con7", "Con8"))

filter(litters_data, pups_born_alive >= 4, pups_born_alive <= 6)

filter(litters_data, gd0_weight + gd18_weight < 70)

filter(litters_data, gd0_weight < gd18_weight)

# don't do this to filter the missing values:
#filter(litters_data, !is.na(gd0_weight))

drop_na(litters_data)

drop_na(litters_data, gd0_weight)
```

## Mutate

```{r}
mutate(litters_data, wt_gain = gd18_weight - gd0_weight)

mutate(
  litters_data, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group),
  group = str_to_upper(group)
)
```

Mutating is great ... But I don't have more examples.

## Arrange

```{r}
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

#arrange according to a few different things:
arrange(litters_data, pups_born_alive, gd0_weight)
```

## pipe ...

Create a collection of commands ...

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = 
  mutate(
    litters_data_selected_cols, 
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
litters_data_with_vars_without_missing = 
  drop_na(litters_data_with_vars, wt_gain)
litters_data_with_vars_without_missing
```

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>% 
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)
```

```{r, eval = FALSE}
litters_data %>% view()

litters_data %>% pull(gd0_weight) %>% mean
```


Don't worry about this much right now.

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names(dat = .) %>% 
  select(.data = ., -pups_survive) %>% 
  lm(gd0_weight ~ gd18_weight, data = .)
```

